import streamlit as st
with st.sidebar:
    st.write("Prénoms: Mame Guiniane")
    st.write("Nom: THIAW")
    st.write("Mail: mameguiniane2701@gmail.com")
    st.write("Téléphone: 773525434")
    
st.header("PROFIL")
st.markdown("""Géographe Aménagiste et Technicienne Supérieure en Géomatique""")
st.write("Je suis offreuse de service dans les domaines liés à la géomatique. Mon travail consiste à apporter mon savoir faire dans vos projets et en tirer de l'expérience en retour.")

st.subheader("FORMATIONS")
st.markdown(""" * Brevet de Technicien Supérieur en Géomatique""")
st.write ("Cours pratiques sur les outils de la Géomatique")
st.markdown(""" * Licence en Géographie""")
st.write ("Aménagement et gestion urbaine en Afrique")
st.write("Prospective territoriale et aménagement")
st.markdown(""" * Baccalauréat""")
st.write("Sciences Sociales")
st.write("Mention: Assez-bien")

st.subheader("COMPETENCES")
st.markdown(""" * SIG""")
st.write("Collecte de données sur le terrain")
st.write("Traitement de données")
st.write("Conception de cartes")
st.write("Requête SQL")
st.markdown(""" * Architecture""")
st.write("Conception des plans selon les normes urbaines")
st.markdown(""" * Topographie""")
st.write("Station totale")
st.write("Théodolite")
st.write("Levée topographique")
st.markdown(""" * Informatique""")
st.write("Suite bureautique")
st.markdown(""" * Programmation""")
st.write("Création d'applications")
st.write("Développeur SIG")
